import Head from 'next/head'
import Nav from "./nav.jsx";

export default function Layout({children}){
    return (
        <>
        <Head>
        <title>E-Commerce</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="description" content="Online Clothes" />
        <link rel="icon" href="/e-commerce.ico" />
        </Head>
        <Nav />
        <div className="pt-16 w-screen h-screen">
            <main className="w-full h-full flex items-center justify-center">
                {children}
            </main>
        </div>
        </>
    )
}

